["SHOW CREATE TABLE books;"]

SELECT COLUMN_NAME, COLUMN_TYPE, COLUMKEY, IS_NULLABLE, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store' AND TABLE_NAME = 'Books';